### ISSUE TITLE
[IO] Refactor Tracking

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#153]
- [x] make iter more consistent with cxxnet structure
- [x] Use NDArray store as mean image
- [x] The Tensor Process moved to ImageNormalizeIter
- [x] The creator macro is simplified.
- [x] Catch exception at least file loading error, c.f. #150 Consider open the file in init function, instead of child thread

@antinucleon @winstywang @sneakerkg 

The commit is pushed to master directly due to my mistake. I won't revert it for now https://github.com/dmlc/mxnet/commit/0e02bd7ecd7db8ad2bce7b7e5eb070c2afda11e6

Please take a review and test if the new setting si correct.

**Comment by tqchen** [comment]
The path error is fixed by #168
