### ISSUE TITLE
[Scala] MXNet on DataFlow

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#1637]
Following effort on [XGBoost on DataFlow](http://dmlc.ml/2016/03/14/xgboost4j-portable-distributed-xgboost-in-spark-flink-and-dataflow.html), we get some experience on how things can be done.

General Work Flow
-------------------------
- Step 1: call ```StartTracker``` on driver side. StartTracker starts the process of tracker(in our case PSScheduler), and  return a ```Map<String, String>```, which contains env variables to initialize server and workers.
- Step 2: Start server part, by calling something like ( range(n) is a dummy data that contains n rows)
```scala
range(n).mapPartition(numServer=n, serverId => {
    envFromDriver.put("DMLC_ROLE", "server");
    envFromDriver.put("DMLC_TASK_ID", serverId);    
    MXNetPSInit(envFromDriver);
})   
```
- Step 3: Start workers, by calling
```scala
rdata.mapPartitionWithIndex(data, serverId => {
    envFromDriver.put("DMLC_ROLE", "worker");
    envFromDriver.put("DMLC_TASK_ID", serverId);    
    MXNetPSInit(envFromDriver);
})   
```

For server jobs, use mapPartition on dummy data, note this need to start in concurrently with worker jobs, possibly from another thread. For Flink, use SrcOperator which don't have data input.

Core API Change
----------------------
cc @mli 
- Being able to call ```PSSchedulerStart``` to start default scheduler, and return the env variables.
- Being able to call ```PSSchedulerStop``` to stop the scheduler.
- Being able to initialize PS by passing configs from chars ```PSInit(int argc, const char **keys, const char **values)``` instead of env variable.

Scala API support
-----------------------
@javelinjs 
- Support stand-alone distributed workflow.

RoadMap
------------
- [x] Add core C API, to either mxnet's or ps-lite's C API
- [x] Standalone distributed workflow
- [x] Try toy example on Spark/Flink

Please @mli @javelinjs  answer to this issue if you have ideas or things unclear. The API change will mainly be done by me and @mli , and scala side effort will mainly lead by @javelinjs , others are welcomed to participate.

**Comment by javelinjs** [comment]
Great to see the issue. Looking forward to the c api.
Also I will test distributed training on multi-machines with scala package these days.

**Comment by futurely** [comment]
Google has recently proposed Apache Beam to provide a unified programming model for distributed execution engines including DataFlow, Spark and Flink. It aims to abstract out the API differences of the various frameworks and should be a more preferable choice.

**Comment by futurely** [comment]
Also notable is [Splash](http://zhangyuc.github.io/splash/) from the UC Berkeley AMPLab. Although the project is still in very early stage, its performance has already been more than a magnitude faster than Spark's MLlib.

The proposed [API](http://zhangyuc.github.io/splash/api/) is general enough to integrate MXNet as the concrete algorithm execution engine.

**Comment by tqchen** [comment]
Thanks for the feedback. There is less important on what to be supported first. Since once one platform is supported, adding another support will be hundreds lines of code

**Comment by javelinjs** [comment]
Can I close this issue?
