### ISSUE TITLE
Recent RoadMap

### ISSUE THREAD

**Issue by antinucleon** [dmlc/mxnet#206]
- [x] modify clip, add dot
- [ ] ndarray trans
- [x] more math functions for ndarray
- [ ] interface for making optimization algo as a single ndarray op
- [x] complex example: adversary
- [x] lstm by using symbol/narray
- [ ] general rnn interface
- [ ] add sum, support loss symbol
- [ ] sparse support [together with mshadow]
- [ ] cusolver support [to ndarray]
- [ ] more visualization
- [ ] launch kernel directly in OP

**Comment by pluskid** [comment]
What is cusolver referring to?

**Comment by antinucleon** [comment]
SVD stuff

**Comment by pluskid** [comment]
I see. Thanks!

**Comment by loveisp** [comment]
I am interested in the part of "more visualization". How is the progress now? What methods are you ready to implement? Maybe I also could contribute some code.

**Comment by antinucleon** [comment]
@loveisp Great thanks Dai! I have done nothing yet. You are more than welcome to PR to https://github.com/dmlc/mxnet/blob/master/python/mxnet/visualization.py . Currently I think we need some functions to visualize filer, feature map and rnn structure. If you have more great ideas, feel free to PR!

**Comment by loveisp** [comment]
@antinucleon OK, I will try to PR:)

**Comment by mli** [comment]
what's the example we are going to show lstm? i vote for char-lstm, char-level language model. https://github.com/karpathy/char-rnn

**Comment by antinucleon** [comment]
I have made a PTB example
https://github.com/antinucleon/mxnet/blob/master/example/LSTM/PennTree.ipynb
, however the behavior is abnormal when compared to torch.


At first 0.8 round, it is almost same to torch one, then torch make
perplexity from 700 to 300 in the last 0.2 of the first round, but ours
reduce from 700 to 670.


I spent a whole day on it and no luck to find out the reason.

**Comment by mli** [comment]
have you tried gradient clipping? it often helps a lot for rnn

**Comment by antinucleon** [comment]
I tested in various clip / norm setting, no effect

**Comment by futurely** [comment]
Would you please provide an example similar to @Russell91's [LSTMSummation built on apollocaffe](https://github.com/Russell91/LSTMSummation) which is more like a hello world of LSTM. It's much easier to debug and will get merged into the master branch sooner. Thanks a lot!

**Comment by antinucleon** [comment]
@futurely Thanks for your suggestion. I think I have located the bug and will fix in today or tmr

**Comment by futurely** [comment]
Great! May I further request an implementation of Bidirectional LSTM? Many papers have shown that it outperforms LSTM in language modelling, speech recognition, OCR and some other applications. There are implementations in [imperative programs](https://github.com/search?q=bidirectional+lstm&type=Code&utf8=%E2%9C%93) but almost none in symbolic programs.

**Comment by antinucleon** [comment]
@futurely Definitely. There will be bi-direction, IRNN, GRU and LSTM examples

**Comment by futurely** [comment]
Your response time is awesome. In a currently very popular competing project, PRs can be open for months.

**Comment by zachmayer** [comment]
I was wondering where I could find the GRU examples?

**Comment by xlvector** [comment]
@futurely Do you have Bidirectional LSTM example?

**Comment by futurely** [comment]
No MXNet version. https://github.com/search?utf8=%E2%9C%93&q=bidirectional+lstm

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/pull/2096
