### ISSUE TITLE
[R, Windows] Process Tracking

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#329]
- [ ] Have a configure.win in the src to search the library, put things(libmxnet.dll) in right position
- [ ] Proper error message to tell user what to install when things do not exist.
- [ ] Ideally only compile the  x64 version.
- [ ] A Makefile option winRpack, to pack a binary distributable version of package.
     - We can ship libmxnet.dll, but need to assume all thirdparty dlls are on path.
     - It is also fine to assume libmxnet.dll is on path, if we treat it as a library(maybe easier for us to go CRAN).

**Comment by tqchen** [comment]
close due to a bit outdated, reopen later
