### ISSUE TITLE
Engine Issue Tracking

### ISSUE THREAD

**Issue by hotpxl** [dmlc/mxnet#56]
- [x] Use C style callback
- [x] Move dispatcher code outside of lock
- [x] Implement `PushAsync` for `NaiveEngine`
- [x]  Isolate out the scheduling part and running policy.
       - The DoPushToQueue logic can be isolated out, as subclass
       - This enables multiple threading policies in for DoPushToQueue

**Comment by tqchen** [comment]
C style callback and PushAsync is done in #63

**Comment by tqchen** [comment]
Dispatcher is moved outside of lock scope in #67

**Comment by tqchen** [comment]
The dispatcher bug is fixed in #69 , now things all out of lock scope.

**Comment by tqchen** [comment]
It turns out there is another BUG in dispatcher, when things are outside lock scope. The code replied on ```to_delete_```, which could change. 

The bugfix is in https://github.com/tqchen/mxnet/commit/bd36bbc1c2a49924385489bcdbe63c71dbf8c559

**Comment by tqchen** [comment]
Close this for now, will open new issue if new problem emerges
